name: CI
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -run: pip3 install -r requirements.txt
            -run: pip3 install flake8
            -run: flake8 main.py

on: [push]
jobs:
    doctest:
        runs-on: ubuntu-latest
        steps:
            -run: python3 -m doctest main.py
    