name: CI
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: pip3 install -r requirements.txt
            - run: pip3 install flake8
            - run: flake8 main.py
    doctest:
            runs-on: ubuntu-latest
            steps:
                - run: python3 -m doctest main.py
    